server:
  port: ${PORT:5000}

spring:
  application:
    name: REGISTRATION_SYSTEM

  profiles:
    active: prod

  datasource:
    url: ${JDBC_DATABASE_URL}
    password: ${JDBC_DATABASE_PASSWORD}
    username: ${JDBC_DATABASE_USERNAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect